name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gh:
    runs-on: ubuntu-latest
    container:
      image: cimg/python:3.11.5
      volumes:
        - /usr/bin/gh:/usr/bin/gh
    defaults:
      run:
        working-directory: ./.github
    
    steps:
      - uses: actions/checkout@v3

      - name: step1
        run: |
          pwd
          python --version
          gh --version

      - name: step1
        working-directory: .
        run: |
          pwd
          python --version
          gh --version  