name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  gh:
    runs-on: ubuntu-latest
    container:
      image: cimg/python:3.11.5

    steps:
      - uses: actions/checkout@v3

      - name: Check version
        run: |
          python --version
          gh --version